# Generated by Django 3.2.8 on 2021-10-08 18:34

import API.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('property_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to=API.utils.get_input_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSegmentation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('front_input_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_output_image_path)),
                ('side_input_image', models.FileField(blank=True, null=True, upload_to=API.utils.get_output_image_path)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('neck', models.FloatField(default=0)),
                ('chest', models.FloatField(default=0)),
                ('waist', models.FloatField(default=0)),
                ('hip', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('arm', models.FloatField(default=0)),
                ('leg', models.FloatField(default=0)),
            ],
        ),
    ]
