# Generated by Django 3.2.8 on 2021-10-15 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_measurement_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesegmentation',
            old_name='front_input_image',
            new_name='input_image',
        ),
        migrations.RemoveField(
            model_name='imagesegmentation',
            name='side_input_image',
        ),
    ]
